# Bun configuration file
# See: https://bun.sh/docs/runtime/bunfig

[install]
# Package installation settings
registry = "https://registry.npmjs.org/"
cache = true
optional = true
peer = true
production = false

[run]
# Runtime configuration
shell = "bash"
bun = true

[test]
# Test runner configuration
coverage = true
timeout = 30000
preload = []

[build]
# Build configuration
target = "node"
format = "esm"
splitting = false
minify = false
sourcemap = true

# Environment-specific settings
[dev]
watch = true
hot = true
